Ustawienie podstawowych nagłówków security
CodersCommunity/forum.pasja-informatyki.local pull request #220
Opened 2020-08-19 11:59 UTC by event15

Myślę, że te nagłówki można z miejsca dodać bez większych problemów.

2020-08-19 12:14 UTC, event15 commented
Zastanawiam się jeszcze nad: 
`Upgrade-Insecure-Requests: 1`

2020-08-20 12:01 UTC, Comandeer requested changes

2020-08-20 12:15 UTC, event15 commented on forum/.htaccess
> +    Header set X-XSS-Protection "1; mode=block"
OK, rozumiem, że chodzi tylko o X-XSS-Protection, jednak nawet Github czy inne większe serwisy mają go. Teraz pytanie pozostaje - czy skoro zostało to usunięte z chromium, to inne serwisy z opóźnieniem się dostosują, czy zostawią "na zaśkę"? Nie uprę się przy tym, żeby to usunąć. Rozważam plusy i minusy. A Firefox, Opera i Safari usunęły to u siebie?

2020-08-20 12:15 UTC, event15 commented on forum/.htaccess
> +    Header set X-Frame-Options "DENY"
Czy jeśli będzie w CSP to będzie to implikować usunięcie tego z headerów, czy powinno być w obu miejscach?

2020-08-20 13:55 UTC, event15 commented on forum/.htaccess
> +    Header set X-Frame-Options "DENY"
Jeśli chodzi o X-Frame-Options - to wnioskuję z tego co podlinkowałeś, że warto przynajmniej teraz jeszcze zachować ten nagłówek przy dodaniu w CSP. Część niezaktualizowanych wersji przeglądarek jeszcze wspiera ten nagłówek a wpis w CSP będzie unieważniać go. 

Jeśli chodzi o `Upgrade-Insecure-Requests` -> wydaje mi się, że też z powodzeniem można stosować nagłówek i CSP. 
Rozumiem z tego wszystkiego, że CSP jest bardziej preferowane.

2020-08-20 17:50 UTC, event15 commented
@awaluk @Comandeer małe podsumowanie:

- przygotowałem link na report-uri do raportowania błędów csp
- zostawiam na chwilę obecną `X-XSS-Protection`
- robię `unset X-Powered-By`
- ustawiłem `Expect-CT "max-age=0, report-uri=\"https://forumpasjainformatyki.report-uri.com/r/d/ct/reportOnly\""` zgodnie z https://scotthelme.co.uk/certificate-transparency-an-introduction/ czyli kolejnym etapem byłoby ustawienie `enforce` z czasem 30 np.
- CSP ustawiłem na report-only w raz z linkiem raportowania do wizzarda https://report-uri.com/ - to mi pomoże ogarnąć bajzel jaki mamy na forum i pozwoli przystosować reguły maksymalnie dobrze (przynajmniej mam taką nadzieję).
- Ustawiłem HSTS bez includeSubdomains i bez preload - wydaje mi się to sensowne.

Czekam na krytykę i opinie.

2020-08-20 22:28 UTC, event15 commented
Na chwile obecną wygenerowałem sobie firefoxem takie CSP:
```
 default-src 'none';
 connect-src 'self' https://pagead2.googlesyndication.com/getconfig/sodar wss://forum.pasja-informatyki.pl:3000;
 font-src 'self' https://fonts.gstatic.com;
 frame-src https://googleads.g.doubleclick.net https://tpc.googlesyndication.com https://www.facebook.com;
 img-src 'self' data: https://forum.pasja-informatyki.pl https://pagead2.googlesyndication.com https://www.google-analytics.com https://www.gravatar.com;
 script-src 'self' 'unsafe-eval' 'unsafe-inline' https://adservice.google.com/adsid/integrator.js https://adservice.google.pl/adsid/integrator.js https://cdn.ampproject.org/rtv/012008102328000/amp4ads-host-v0.js https://connect.facebook.net/pl_PL/sdk.js https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js https://pagead2.googlesyndication.com/pagead/js/r20200817/r20190131/show_ads_impl_fy2019.js https://pagead2.googlesyndication.com/pagead/js/r20200818/r20190131/show_ads_impl_fy2019.js https://tpc.googlesyndication.com/sodar/sodar2.js https://www.google-analytics.com/analytics.js https://www.googletagservices.com/activeview/js/current/osd.js;
 style-src 'self' 'unsafe-inline' https://fonts.googleapis.com/ 
```

Brakuje jeszcze iframek i upgrade security, ale generator bierze pod uwage tylko określone tagi.

2020-08-20 22:54 UTC, Comandeer commented on forum/.htaccess
> +    Header set X-XSS-Protection "1; mode=block"
https://groups.google.com/a/chromium.org/g/blink-dev/c/TuYw-EZhO9g/m/blGViehIAwAJ?pli=1

> other browsers do not support this

2020-08-20 22:59 UTC, Comandeer commented on forum/.htaccess
> +    Header set X-Frame-Options "DENY"
Nie ma praktycznie na rynku przeglądarek, które nie rozumiałyby wersji CSP – jedyna nieaktualizująca się przeglądarka to IE – nie wiem, czy jest jakaś wartość dodana w tym dodatkowym nagłówku.

2020-08-20 23:04 UTC, event15 commented on forum/.htaccess
> +    Header set X-Frame-Options "DENY"
https://observatory.mozilla.org/analyze/forum.pasja-informatyki.pl -> technicznie, część checkerów sprawdza te nagłówki i ten x-xss-protection też. 
Tu x-frame-options https://securityheaders.com/?q=https%3A%2F%2Fforum.pasja-informatyki.pl%2F&followRedirects=on

2020-08-23 19:53 UTC, event15 commented on forum/.htaccess
> +    Header set X-Frame-Options "DENY"
po testach okazuje się, że musi być 
`Header set X-Frame-Options "SameOrigin"`

2023-07-21 20:21 UTC, awaluk commented
Część zmian z tego była wdrożona lub testowana, część już nieaktualna, trzeba byłoby podejść do tego na nowo - zamykam

2023-07-21 20:21 UTC, closed without merging